# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CharakterEquipment.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_formAusruestung(object):
    def setupUi(self, formAusruestung):
        formAusruestung.setObjectName("formAusruestung")
        formAusruestung.resize(701, 409)
        self.gridLayoutWidget = QtWidgets.QWidget(formAusruestung)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 701, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 1, 1, 1)
        self.spinW3rw = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW3rw.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW3rw.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW3rw.setMaximum(99)
        self.spinW3rw.setObjectName("spinW3rw")
        self.gridLayout_3.addWidget(self.spinW3rw, 3, 4, 1, 1)
        self.spinW5rw = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW5rw.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW5rw.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW5rw.setMaximum(99)
        self.spinW5rw.setObjectName("spinW5rw")
        self.gridLayout_3.addWidget(self.spinW5rw, 5, 4, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.spinW3w6 = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinW3w6.sizePolicy().hasHeightForWidth())
        self.spinW3w6.setSizePolicy(sizePolicy)
        self.spinW3w6.setMinimumSize(QtCore.QSize(15, 0))
        self.spinW3w6.setMaximumSize(QtCore.QSize(15, 16777215))
        self.spinW3w6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinW3w6.setObjectName("spinW3w6")
        self.horizontalLayout_7.addWidget(self.spinW3w6)
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_7.addWidget(self.label_35)
        self.spinW3plus = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinW3plus.sizePolicy().hasHeightForWidth())
        self.spinW3plus.setSizePolicy(sizePolicy)
        self.spinW3plus.setMinimumSize(QtCore.QSize(15, 0))
        self.spinW3plus.setMaximumSize(QtCore.QSize(15, 16777215))
        self.spinW3plus.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinW3plus.setObjectName("spinW3plus")
        self.horizontalLayout_7.addWidget(self.spinW3plus)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 3, 3, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.spinW4w6 = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinW4w6.sizePolicy().hasHeightForWidth())
        self.spinW4w6.setSizePolicy(sizePolicy)
        self.spinW4w6.setMinimumSize(QtCore.QSize(15, 0))
        self.spinW4w6.setMaximumSize(QtCore.QSize(15, 16777215))
        self.spinW4w6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinW4w6.setObjectName("spinW4w6")
        self.horizontalLayout_8.addWidget(self.spinW4w6)
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_8.addWidget(self.label_36)
        self.spinW4plus = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinW4plus.sizePolicy().hasHeightForWidth())
        self.spinW4plus.setSizePolicy(sizePolicy)
        self.spinW4plus.setMinimumSize(QtCore.QSize(15, 0))
        self.spinW4plus.setMaximumSize(QtCore.QSize(15, 16777215))
        self.spinW4plus.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinW4plus.setObjectName("spinW4plus")
        self.horizontalLayout_8.addWidget(self.spinW4plus)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 4, 3, 1, 1)
        self.spinW1h = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW1h.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW1h.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW1h.setMinimum(1)
        self.spinW1h.setMaximum(12)
        self.spinW1h.setProperty("value", 6)
        self.spinW1h.setObjectName("spinW1h")
        self.gridLayout_3.addWidget(self.spinW1h, 1, 7, 1, 1)
        self.editW1eig = QtWidgets.QLineEdit(self.groupBox_2)
        self.editW1eig.setObjectName("editW1eig")
        self.gridLayout_3.addWidget(self.editW1eig, 1, 8, 1, 1)
        self.spinW1rw = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW1rw.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW1rw.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW1rw.setMaximum(99)
        self.spinW1rw.setObjectName("spinW1rw")
        self.gridLayout_3.addWidget(self.spinW1rw, 1, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 8, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.spinW2w6 = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinW2w6.sizePolicy().hasHeightForWidth())
        self.spinW2w6.setSizePolicy(sizePolicy)
        self.spinW2w6.setMinimumSize(QtCore.QSize(15, 0))
        self.spinW2w6.setMaximumSize(QtCore.QSize(15, 16777215))
        self.spinW2w6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinW2w6.setObjectName("spinW2w6")
        self.horizontalLayout_11.addWidget(self.spinW2w6)
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_11.addWidget(self.label_39)
        self.spinW2plus = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinW2plus.sizePolicy().hasHeightForWidth())
        self.spinW2plus.setSizePolicy(sizePolicy)
        self.spinW2plus.setMinimumSize(QtCore.QSize(15, 0))
        self.spinW2plus.setMaximumSize(QtCore.QSize(15, 16777215))
        self.spinW2plus.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinW2plus.setObjectName("spinW2plus")
        self.horizontalLayout_11.addWidget(self.spinW2plus)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 2, 3, 1, 1)
        self.labelWM = QtWidgets.QLabel(self.groupBox_2)
        self.labelWM.setObjectName("labelWM")
        self.gridLayout_3.addWidget(self.labelWM, 0, 6, 1, 1)
        self.spinW1wm = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW1wm.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW1wm.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW1wm.setMinimum(-3)
        self.spinW1wm.setMaximum(16)
        self.spinW1wm.setObjectName("spinW1wm")
        self.gridLayout_3.addWidget(self.spinW1wm, 1, 6, 1, 1)
        self.labelRW1 = QtWidgets.QLabel(self.groupBox_2)
        self.labelRW1.setObjectName("labelRW1")
        self.gridLayout_3.addWidget(self.labelRW1, 0, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 7, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.spinW1w6 = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinW1w6.sizePolicy().hasHeightForWidth())
        self.spinW1w6.setSizePolicy(sizePolicy)
        self.spinW1w6.setMinimumSize(QtCore.QSize(15, 0))
        self.spinW1w6.setMaximumSize(QtCore.QSize(15, 16777215))
        self.spinW1w6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinW1w6.setObjectName("spinW1w6")
        self.horizontalLayout_3.addWidget(self.spinW1w6)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.spinW1plus = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinW1plus.sizePolicy().hasHeightForWidth())
        self.spinW1plus.setSizePolicy(sizePolicy)
        self.spinW1plus.setMinimumSize(QtCore.QSize(15, 0))
        self.spinW1plus.setMaximumSize(QtCore.QSize(15, 16777215))
        self.spinW1plus.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinW1plus.setObjectName("spinW1plus")
        self.horizontalLayout_3.addWidget(self.spinW1plus)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 3, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.spinW5w6 = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinW5w6.sizePolicy().hasHeightForWidth())
        self.spinW5w6.setSizePolicy(sizePolicy)
        self.spinW5w6.setMinimumSize(QtCore.QSize(15, 0))
        self.spinW5w6.setMaximumSize(QtCore.QSize(15, 16777215))
        self.spinW5w6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinW5w6.setObjectName("spinW5w6")
        self.horizontalLayout_9.addWidget(self.spinW5w6)
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_9.addWidget(self.label_37)
        self.spinW5plus = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinW5plus.sizePolicy().hasHeightForWidth())
        self.spinW5plus.setSizePolicy(sizePolicy)
        self.spinW5plus.setMinimumSize(QtCore.QSize(15, 0))
        self.spinW5plus.setMaximumSize(QtCore.QSize(15, 16777215))
        self.spinW5plus.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinW5plus.setObjectName("spinW5plus")
        self.horizontalLayout_9.addWidget(self.spinW5plus)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 5, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 3, 1, 1)
        self.editW2name = QtWidgets.QLineEdit(self.groupBox_2)
        self.editW2name.setObjectName("editW2name")
        self.gridLayout_3.addWidget(self.editW2name, 2, 1, 1, 1)
        self.spinW2rw = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW2rw.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW2rw.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW2rw.setMaximum(99)
        self.spinW2rw.setObjectName("spinW2rw")
        self.gridLayout_3.addWidget(self.spinW2rw, 2, 4, 1, 1)
        self.spinW4rw = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW4rw.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW4rw.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW4rw.setMaximum(99)
        self.spinW4rw.setObjectName("spinW4rw")
        self.gridLayout_3.addWidget(self.spinW4rw, 4, 4, 1, 1)
        self.spinW2h = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW2h.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW2h.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW2h.setMinimum(1)
        self.spinW2h.setMaximum(12)
        self.spinW2h.setProperty("value", 6)
        self.spinW2h.setObjectName("spinW2h")
        self.gridLayout_3.addWidget(self.spinW2h, 2, 7, 1, 1)
        self.spinW3h = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW3h.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW3h.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW3h.setMinimum(1)
        self.spinW3h.setMaximum(12)
        self.spinW3h.setProperty("value", 6)
        self.spinW3h.setObjectName("spinW3h")
        self.gridLayout_3.addWidget(self.spinW3h, 3, 7, 1, 1)
        self.editW3name = QtWidgets.QLineEdit(self.groupBox_2)
        self.editW3name.setObjectName("editW3name")
        self.gridLayout_3.addWidget(self.editW3name, 3, 1, 1, 1)
        self.editW2eig = QtWidgets.QLineEdit(self.groupBox_2)
        self.editW2eig.setObjectName("editW2eig")
        self.gridLayout_3.addWidget(self.editW2eig, 2, 8, 1, 1)
        self.editW5eig = QtWidgets.QLineEdit(self.groupBox_2)
        self.editW5eig.setObjectName("editW5eig")
        self.gridLayout_3.addWidget(self.editW5eig, 5, 8, 1, 1)
        self.spinW3wm = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW3wm.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW3wm.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW3wm.setMinimum(-3)
        self.spinW3wm.setMaximum(16)
        self.spinW3wm.setObjectName("spinW3wm")
        self.gridLayout_3.addWidget(self.spinW3wm, 3, 6, 1, 1)
        self.spinW4h = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW4h.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW4h.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW4h.setMinimum(1)
        self.spinW4h.setMaximum(12)
        self.spinW4h.setProperty("value", 6)
        self.spinW4h.setObjectName("spinW4h")
        self.gridLayout_3.addWidget(self.spinW4h, 4, 7, 1, 1)
        self.editW4name = QtWidgets.QLineEdit(self.groupBox_2)
        self.editW4name.setObjectName("editW4name")
        self.gridLayout_3.addWidget(self.editW4name, 4, 1, 1, 1)
        self.spinW4wm = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW4wm.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW4wm.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW4wm.setMinimum(-3)
        self.spinW4wm.setMaximum(16)
        self.spinW4wm.setObjectName("spinW4wm")
        self.gridLayout_3.addWidget(self.spinW4wm, 4, 6, 1, 1)
        self.spinW5h = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW5h.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW5h.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW5h.setMinimum(1)
        self.spinW5h.setMaximum(12)
        self.spinW5h.setProperty("value", 6)
        self.spinW5h.setObjectName("spinW5h")
        self.gridLayout_3.addWidget(self.spinW5h, 5, 7, 1, 1)
        self.spinW5wm = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW5wm.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW5wm.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW5wm.setMinimum(-3)
        self.spinW5wm.setMaximum(16)
        self.spinW5wm.setObjectName("spinW5wm")
        self.gridLayout_3.addWidget(self.spinW5wm, 5, 6, 1, 1)
        self.editW4eig = QtWidgets.QLineEdit(self.groupBox_2)
        self.editW4eig.setObjectName("editW4eig")
        self.gridLayout_3.addWidget(self.editW4eig, 4, 8, 1, 1)
        self.editW5name = QtWidgets.QLineEdit(self.groupBox_2)
        self.editW5name.setObjectName("editW5name")
        self.gridLayout_3.addWidget(self.editW5name, 5, 1, 1, 1)
        self.editW3eig = QtWidgets.QLineEdit(self.groupBox_2)
        self.editW3eig.setObjectName("editW3eig")
        self.gridLayout_3.addWidget(self.editW3eig, 3, 8, 1, 1)
        self.editW1name = QtWidgets.QLineEdit(self.groupBox_2)
        self.editW1name.setObjectName("editW1name")
        self.gridLayout_3.addWidget(self.editW1name, 1, 1, 1, 1)
        self.spinW2wm = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW2wm.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW2wm.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW2wm.setMinimum(-3)
        self.spinW2wm.setMaximum(16)
        self.spinW2wm.setObjectName("spinW2wm")
        self.gridLayout_3.addWidget(self.spinW2wm, 2, 6, 1, 1)
        self.checkW1FK = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkW1FK.setText("")
        self.checkW1FK.setObjectName("checkW1FK")
        self.gridLayout_3.addWidget(self.checkW1FK, 1, 0, 1, 1)
        self.spinW3rw2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW3rw2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW3rw2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW3rw2.setMaximum(500)
        self.spinW3rw2.setObjectName("spinW3rw2")
        self.gridLayout_3.addWidget(self.spinW3rw2, 3, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.checkW5FK = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkW5FK.setText("")
        self.checkW5FK.setObjectName("checkW5FK")
        self.gridLayout_3.addWidget(self.checkW5FK, 5, 0, 1, 1)
        self.checkW3FK = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkW3FK.setText("")
        self.checkW3FK.setObjectName("checkW3FK")
        self.gridLayout_3.addWidget(self.checkW3FK, 3, 0, 1, 1)
        self.labelRW2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelRW2.setObjectName("labelRW2")
        self.gridLayout_3.addWidget(self.labelRW2, 0, 5, 1, 1)
        self.checkW2FK = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkW2FK.setText("")
        self.checkW2FK.setObjectName("checkW2FK")
        self.gridLayout_3.addWidget(self.checkW2FK, 2, 0, 1, 1)
        self.spinW1rw2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW1rw2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW1rw2.setReadOnly(False)
        self.spinW1rw2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW1rw2.setMaximum(500)
        self.spinW1rw2.setObjectName("spinW1rw2")
        self.gridLayout_3.addWidget(self.spinW1rw2, 1, 5, 1, 1)
        self.checkW4FK = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkW4FK.setText("")
        self.checkW4FK.setObjectName("checkW4FK")
        self.gridLayout_3.addWidget(self.checkW4FK, 4, 0, 1, 1)
        self.spinW2rw2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW2rw2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW2rw2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW2rw2.setMaximum(500)
        self.spinW2rw2.setObjectName("spinW2rw2")
        self.gridLayout_3.addWidget(self.spinW2rw2, 2, 5, 1, 1)
        self.spinW4rw2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW4rw2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW4rw2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW4rw2.setMaximum(500)
        self.spinW4rw2.setObjectName("spinW4rw2")
        self.gridLayout_3.addWidget(self.spinW4rw2, 4, 5, 1, 1)
        self.spinW5rw2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinW5rw2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW5rw2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW5rw2.setMaximum(500)
        self.spinW5rw2.setObjectName("spinW5rw2")
        self.gridLayout_3.addWidget(self.spinW5rw2, 5, 5, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout.addWidget(self.groupBox_2, 3, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(35, 0))
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setMinimumSize(QtCore.QSize(35, 0))
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(35, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(35, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 8, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMinimumSize(QtCore.QSize(35, 0))
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMinimumSize(QtCore.QSize(35, 0))
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(35, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 7, 1, 1)
        self.spinR1rarm = QtWidgets.QSpinBox(self.groupBox)
        self.spinR1rarm.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR1rarm.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR1rarm.setMaximum(8)
        self.spinR1rarm.setObjectName("spinR1rarm")
        self.gridLayout_2.addWidget(self.spinR1rarm, 1, 5, 1, 1)
        self.spinR2bein = QtWidgets.QSpinBox(self.groupBox)
        self.spinR2bein.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR2bein.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR2bein.setMaximum(8)
        self.spinR2bein.setObjectName("spinR2bein")
        self.gridLayout_2.addWidget(self.spinR2bein, 2, 3, 1, 1)
        self.spinR1bein = QtWidgets.QSpinBox(self.groupBox)
        self.spinR1bein.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR1bein.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR1bein.setMaximum(8)
        self.spinR1bein.setObjectName("spinR1bein")
        self.gridLayout_2.addWidget(self.spinR1bein, 1, 3, 1, 1)
        self.spinR1larm = QtWidgets.QSpinBox(self.groupBox)
        self.spinR1larm.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR1larm.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR1larm.setMaximum(8)
        self.spinR1larm.setObjectName("spinR1larm")
        self.gridLayout_2.addWidget(self.spinR1larm, 1, 4, 1, 1)
        self.spinR1bauch = QtWidgets.QSpinBox(self.groupBox)
        self.spinR1bauch.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR1bauch.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR1bauch.setMaximum(8)
        self.spinR1bauch.setObjectName("spinR1bauch")
        self.gridLayout_2.addWidget(self.spinR1bauch, 1, 6, 1, 1)
        self.editR1name = QtWidgets.QLineEdit(self.groupBox)
        self.editR1name.setObjectName("editR1name")
        self.gridLayout_2.addWidget(self.editR1name, 1, 0, 1, 1)
        self.spinR2bauch = QtWidgets.QSpinBox(self.groupBox)
        self.spinR2bauch.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR2bauch.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR2bauch.setMaximum(8)
        self.spinR2bauch.setObjectName("spinR2bauch")
        self.gridLayout_2.addWidget(self.spinR2bauch, 2, 6, 1, 1)
        self.spinR1kopf = QtWidgets.QSpinBox(self.groupBox)
        self.spinR1kopf.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR1kopf.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR1kopf.setMaximum(8)
        self.spinR1kopf.setObjectName("spinR1kopf")
        self.gridLayout_2.addWidget(self.spinR1kopf, 1, 8, 1, 1)
        self.spinR2be = QtWidgets.QSpinBox(self.groupBox)
        self.spinR2be.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR2be.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR2be.setMaximum(8)
        self.spinR2be.setObjectName("spinR2be")
        self.gridLayout_2.addWidget(self.spinR2be, 2, 1, 1, 1)
        self.spinR2larm = QtWidgets.QSpinBox(self.groupBox)
        self.spinR2larm.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR2larm.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR2larm.setMaximum(8)
        self.spinR2larm.setObjectName("spinR2larm")
        self.gridLayout_2.addWidget(self.spinR2larm, 2, 4, 1, 1)
        self.spinR1brust = QtWidgets.QSpinBox(self.groupBox)
        self.spinR1brust.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR1brust.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR1brust.setMaximum(8)
        self.spinR1brust.setObjectName("spinR1brust")
        self.gridLayout_2.addWidget(self.spinR1brust, 1, 7, 1, 1)
        self.spinR1be = QtWidgets.QSpinBox(self.groupBox)
        self.spinR1be.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR1be.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR1be.setMaximum(8)
        self.spinR1be.setObjectName("spinR1be")
        self.gridLayout_2.addWidget(self.spinR1be, 1, 1, 1, 1)
        self.spinR2rarm = QtWidgets.QSpinBox(self.groupBox)
        self.spinR2rarm.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR2rarm.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR2rarm.setMaximum(8)
        self.spinR2rarm.setObjectName("spinR2rarm")
        self.gridLayout_2.addWidget(self.spinR2rarm, 2, 5, 1, 1)
        self.editR2name = QtWidgets.QLineEdit(self.groupBox)
        self.editR2name.setObjectName("editR2name")
        self.gridLayout_2.addWidget(self.editR2name, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 1, 1)
        self.spinR2kopf = QtWidgets.QSpinBox(self.groupBox)
        self.spinR2kopf.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR2kopf.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR2kopf.setMaximum(8)
        self.spinR2kopf.setObjectName("spinR2kopf")
        self.gridLayout_2.addWidget(self.spinR2kopf, 2, 8, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.spinR2brust = QtWidgets.QSpinBox(self.groupBox)
        self.spinR2brust.setAlignment(QtCore.Qt.AlignCenter)
        self.spinR2brust.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinR2brust.setMaximum(8)
        self.spinR2brust.setObjectName("spinR2brust")
        self.gridLayout_2.addWidget(self.spinR2brust, 2, 7, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 1, 1, 1)

        self.retranslateUi(formAusruestung)
        QtCore.QMetaObject.connectSlotsByName(formAusruestung)

    def retranslateUi(self, formAusruestung):
        _translate = QtCore.QCoreApplication.translate
        formAusruestung.setWindowTitle(_translate("formAusruestung", "Form"))
        self.groupBox_2.setTitle(_translate("formAusruestung", "Waffen"))
        self.label_13.setText(_translate("formAusruestung", "Name"))
        self.label_35.setText(_translate("formAusruestung", "W6 +"))
        self.label_36.setText(_translate("formAusruestung", "W6 +"))
        self.label_18.setText(_translate("formAusruestung", "Eigenschaften"))
        self.label_39.setText(_translate("formAusruestung", "W6 +"))
        self.labelWM.setText(_translate("formAusruestung", "WM"))
        self.labelRW1.setText(_translate("formAusruestung", "RW"))
        self.label_17.setText(_translate("formAusruestung", "Härte"))
        self.label_22.setText(_translate("formAusruestung", "W6 +"))
        self.label_37.setText(_translate("formAusruestung", "W6 +"))
        self.label_14.setText(_translate("formAusruestung", "TP"))
        self.label_11.setText(_translate("formAusruestung", "FK"))
        self.labelRW2.setText(_translate("formAusruestung", " - "))
        self.groupBox.setTitle(_translate("formAusruestung", "Rüstungen"))
        self.label_6.setText(_translate("formAusruestung", "Bauch"))
        self.label_8.setText(_translate("formAusruestung", "L. Arm"))
        self.label_3.setText(_translate("formAusruestung", "R. Arm"))
        self.label_5.setText(_translate("formAusruestung", "Kopf"))
        self.label_10.setText(_translate("formAusruestung", "Bein"))
        self.label_7.setText(_translate("formAusruestung", "BE*"))
        self.label_4.setText(_translate("formAusruestung", "Brust"))
        self.label.setText(_translate("formAusruestung", "Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formAusruestung = QtWidgets.QWidget()
    ui = Ui_formAusruestung()
    ui.setupUi(formAusruestung)
    formAusruestung.show()
    sys.exit(app.exec_())

