# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CharakterFertigkeiten.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(872, 460)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(80)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget.verticalHeader().setMinimumSectionSize(40)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setBaseSize(QtCore.QSize(0, 0))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 258, 432))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 2, 3, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 3, 1, 1)
        self.spinSF = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinSF.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinSF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinSF.setReadOnly(True)
        self.spinSF.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinSF.setObjectName("spinSF")
        self.gridLayout_3.addWidget(self.spinSF, 1, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.spinBasis = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBasis.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinBasis.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBasis.setReadOnly(True)
        self.spinBasis.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBasis.setObjectName("spinBasis")
        self.gridLayout_3.addWidget(self.spinBasis, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 3, 1, 1)
        self.spinFW = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinFW.setAlignment(QtCore.Qt.AlignCenter)
        self.spinFW.setReadOnly(False)
        self.spinFW.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinFW.setObjectName("spinFW")
        self.gridLayout_3.addWidget(self.spinFW, 2, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.spinPW = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinPW.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinPW.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinPW.setReadOnly(True)
        self.spinPW.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinPW.setObjectName("spinPW")
        self.gridLayout_3.addWidget(self.spinPW, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 3, 1, 1)
        self.spinPWT = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinPWT.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinPWT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinPWT.setReadOnly(True)
        self.spinPWT.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinPWT.setObjectName("spinPWT")
        self.gridLayout_3.addWidget(self.spinPWT, 3, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 2)
        self.buttonAdd = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonAdd.setMaximumSize(QtCore.QSize(25, 20))
        self.buttonAdd.setObjectName("buttonAdd")
        self.gridLayout_3.addWidget(self.buttonAdd, 4, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listTalente = QtWidgets.QListView(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listTalente.sizePolicy().hasHeightForWidth())
        self.listTalente.setSizePolicy(sizePolicy)
        self.listTalente.setMaximumSize(QtCore.QSize(16777215, 80))
        self.listTalente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listTalente.setObjectName("listTalente")
        self.horizontalLayout.addWidget(self.listTalente)
        self.gridLayout_3.addLayout(self.horizontalLayout, 5, 0, 1, 5)
        self.plainText = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainText.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plainText.setFrameShape(QtWidgets.QFrame.Box)
        self.plainText.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plainText.setLineWidth(1)
        self.plainText.setReadOnly(True)
        self.plainText.setBackgroundVisible(False)
        self.plainText.setObjectName("plainText")
        self.gridLayout_3.addWidget(self.plainText, 6, 0, 1, 5)
        self.labelFertigkeit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelFertigkeit.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFertigkeit.setFont(font)
        self.labelFertigkeit.setObjectName("labelFertigkeit")
        self.gridLayout_3.addWidget(self.labelFertigkeit, 0, 0, 1, 5)
        self.labelAttribute = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelAttribute.setFont(font)
        self.labelAttribute.setObjectName("labelAttribute")
        self.gridLayout_3.addWidget(self.labelAttribute, 1, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tableWidget, self.scrollArea)
        Form.setTabOrder(self.scrollArea, self.spinSF)
        Form.setTabOrder(self.spinSF, self.spinBasis)
        Form.setTabOrder(self.spinBasis, self.spinFW)
        Form.setTabOrder(self.spinFW, self.spinPW)
        Form.setTabOrder(self.spinPW, self.spinPWT)
        Form.setTabOrder(self.spinPWT, self.buttonAdd)
        Form.setTabOrder(self.buttonAdd, self.listTalente)
        Form.setTabOrder(self.listTalente, self.plainText)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Fertigkeitsname"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "FW"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Talente"))
        self.label_5.setText(_translate("Form", "SF:"))
        self.label_6.setText(_translate("Form", "Basis:"))
        self.label_7.setText(_translate("Form", "FW:"))
        self.label_8.setText(_translate("Form", "PW:"))
        self.label.setText(_translate("Form", "PW(T):"))
        self.label_9.setText(_translate("Form", "Erworbene Talente:"))
        self.buttonAdd.setText(_translate("Form", "+"))
        self.labelFertigkeit.setText(_translate("Form", "Fertigkeit"))
        self.labelAttribute.setText(_translate("Form", "Attribute"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
