# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CharakterWaffen.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(445, 309)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWeapons = QtWidgets.QTreeWidget(Dialog)
        self.treeWeapons.setObjectName("treeWeapons")
        self.horizontalLayout.addWidget(self.treeWeapons)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 218, 258))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.labelWM_Desc = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelWM_Desc.setObjectName("labelWM_Desc")
        self.gridLayout.addWidget(self.labelWM_Desc, 4, 0, 1, 1)
        self.labelLZ_Desc = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelLZ_Desc.setObjectName("labelLZ_Desc")
        self.gridLayout.addWidget(self.labelLZ_Desc, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 2)
        self.labelH = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelH.setObjectName("labelH")
        self.gridLayout.addWidget(self.labelH, 6, 2, 1, 1)
        self.labelLZ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelLZ.setObjectName("labelLZ")
        self.gridLayout.addWidget(self.labelLZ, 5, 2, 1, 1)
        self.labelWM = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelWM.setObjectName("labelWM")
        self.gridLayout.addWidget(self.labelWM, 4, 2, 1, 1)
        self.labelRW = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelRW.setObjectName("labelRW")
        self.gridLayout.addWidget(self.labelRW, 3, 2, 1, 1)
        self.labelTP = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelTP.setObjectName("labelTP")
        self.gridLayout.addWidget(self.labelTP, 2, 2, 1, 1)
        self.labelName = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 0, 0, 1, 3)
        self.plainEigenschaften = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainEigenschaften.setReadOnly(True)
        self.plainEigenschaften.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainEigenschaften.setObjectName("plainEigenschaften")
        self.gridLayout.addWidget(self.plainEigenschaften, 8, 0, 1, 3)
        self.labelTyp = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelTyp.setFont(font)
        self.labelTyp.setObjectName("labelTyp")
        self.gridLayout.addWidget(self.labelTyp, 1, 0, 1, 3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sephrasto - Waffe wählen..."))
        self.treeWeapons.headerItem().setText(0, _translate("Dialog", "Name"))
        self.label_4.setText(_translate("Dialog", "Reichweite"))
        self.labelWM_Desc.setText(_translate("Dialog", "Waffenmodifikator"))
        self.labelLZ_Desc.setText(_translate("Dialog", "Ladezeit"))
        self.label_12.setText(_translate("Dialog", "Eigenschaften"))
        self.label_2.setText(_translate("Dialog", "Trefferpunkte"))
        self.label_10.setText(_translate("Dialog", "Härte"))
        self.labelH.setText(_translate("Dialog", "TextLabel"))
        self.labelLZ.setText(_translate("Dialog", "TextLabel"))
        self.labelWM.setText(_translate("Dialog", "TextLabel"))
        self.labelRW.setText(_translate("Dialog", "TextLabel"))
        self.labelTP.setText(_translate("Dialog", "TextLabel"))
        self.labelName.setText(_translate("Dialog", "Waffenname"))
        self.labelTyp.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

