# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CharakterItems.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(872, 460)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setMaxLength(52)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 8, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setMaxLength(52)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 4, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(163, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setMaxLength(52)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 7, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setMaxLength(52)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 6, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setMaxLength(52)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 7, 3, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setMaxLength(52)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_2.addWidget(self.lineEdit_13, 9, 1, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(Form)
        self.lineEdit_19.setMaxLength(52)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_2.addWidget(self.lineEdit_19, 13, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(163, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 4, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_1.setMinimumSize(QtCore.QSize(320, 0))
        self.lineEdit_1.setText("")
        self.lineEdit_1.setMaxLength(52)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout_2.addWidget(self.lineEdit_1, 1, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setMaxLength(52)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 2, 3, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(Form)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_2.addWidget(self.lineEdit_20, 13, 3, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setMaxLength(52)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(Form)
        self.lineEdit_18.setMaxLength(52)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_2.addWidget(self.lineEdit_18, 12, 3, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setMaxLength(52)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 6, 3, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setMaxLength(52)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_2.addWidget(self.lineEdit_16, 11, 3, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setMaxLength(52)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setMaxLength(52)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 8, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(320, 0))
        self.lineEdit_2.setMaxLength(52)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 14, 1, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setMaxLength(52)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_2.addWidget(self.lineEdit_14, 9, 3, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(Form)
        self.lineEdit_17.setMaxLength(52)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_2.addWidget(self.lineEdit_17, 12, 1, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setMaxLength(52)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_2.addWidget(self.lineEdit_15, 11, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_1, self.lineEdit_2)
        Form.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Form.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        Form.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        Form.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        Form.setTabOrder(self.lineEdit_6, self.lineEdit_7)
        Form.setTabOrder(self.lineEdit_7, self.lineEdit_8)
        Form.setTabOrder(self.lineEdit_8, self.lineEdit_9)
        Form.setTabOrder(self.lineEdit_9, self.lineEdit_10)
        Form.setTabOrder(self.lineEdit_10, self.lineEdit_11)
        Form.setTabOrder(self.lineEdit_11, self.lineEdit_12)
        Form.setTabOrder(self.lineEdit_12, self.lineEdit_13)
        Form.setTabOrder(self.lineEdit_13, self.lineEdit_14)
        Form.setTabOrder(self.lineEdit_14, self.lineEdit_15)
        Form.setTabOrder(self.lineEdit_15, self.lineEdit_16)
        Form.setTabOrder(self.lineEdit_16, self.lineEdit_17)
        Form.setTabOrder(self.lineEdit_17, self.lineEdit_18)
        Form.setTabOrder(self.lineEdit_18, self.lineEdit_19)
        Form.setTabOrder(self.lineEdit_19, self.lineEdit_20)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
