# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CharakterVorteile.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(701, 409)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeWidget.setTabKeyNavigation(True)
        self.treeWidget.setProperty("showDropIndicator", False)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setAllColumnsShowFocus(True)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(100)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setMinimumSectionSize(80)
        self.treeWidget.header().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.treeWidget)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setMinimumSize(QtCore.QSize(300, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(225, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 298, 389))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setMinimumSize(QtCore.QSize(0, 18))
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 2)
        self.plainText = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainText.setFrameShape(QtWidgets.QFrame.Box)
        self.plainText.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plainText.setLineWidth(1)
        self.plainText.setReadOnly(True)
        self.plainText.setBackgroundVisible(False)
        self.plainText.setObjectName("plainText")
        self.gridLayout_2.addWidget(self.plainText, 8, 0, 1, 2)
        self.spinKosten = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinKosten.setAlignment(QtCore.Qt.AlignCenter)
        self.spinKosten.setReadOnly(True)
        self.spinKosten.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinKosten.setMinimum(-1000)
        self.spinKosten.setMaximum(1000)
        self.spinKosten.setSingleStep(20)
        self.spinKosten.setObjectName("spinKosten")
        self.gridLayout_2.addWidget(self.spinKosten, 3, 1, 1, 1)
        self.labelTyp = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelTyp.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelTyp.setFont(font)
        self.labelTyp.setObjectName("labelTyp")
        self.gridLayout_2.addWidget(self.labelTyp, 3, 0, 1, 1)
        self.plainVoraussetzungen = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainVoraussetzungen.setMinimumSize(QtCore.QSize(0, 50))
        self.plainVoraussetzungen.setMaximumSize(QtCore.QSize(16777215, 80))
        self.plainVoraussetzungen.setReadOnly(True)
        self.plainVoraussetzungen.setObjectName("plainVoraussetzungen")
        self.gridLayout_2.addWidget(self.plainVoraussetzungen, 6, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.labelNachkauf = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelNachkauf.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelNachkauf.setFont(font)
        self.labelNachkauf.setObjectName("labelNachkauf")
        self.gridLayout_2.addWidget(self.labelNachkauf, 4, 1, 1, 1)
        self.labelVorteil = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelVorteil.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelVorteil.setFont(font)
        self.labelVorteil.setObjectName("labelVorteil")
        self.gridLayout_2.addWidget(self.labelVorteil, 1, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "Vorteil"))
        self.treeWidget.headerItem().setText(1, _translate("Form", "Kosten"))
        self.label_8.setText(_translate("Form", "Voraussetzungen:"))
        self.spinKosten.setSuffix(_translate("Form", " EP"))
        self.labelTyp.setText(_translate("Form", "Profan"))
        self.label.setText(_translate("Form", "Nachkauf:"))
        self.labelNachkauf.setText(_translate("Form", "Häufig"))
        self.labelVorteil.setText(_translate("Form", "Vorteil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

