# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CharakterMinderpakt.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(701, 353)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(425, 0))
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeWidget.setTabKeyNavigation(True)
        self.treeWidget.setProperty("showDropIndicator", False)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setAllColumnsShowFocus(True)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(100)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setMinimumSectionSize(80)
        self.treeWidget.header().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setMinimumSize(QtCore.QSize(250, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(225, 16777215))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setMidLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 246, 300))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelVorteil = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelVorteil.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelVorteil.setFont(font)
        self.labelVorteil.setStyleSheet("margin-left: 1px;")
        self.labelVorteil.setObjectName("labelVorteil")
        self.gridLayout.addWidget(self.labelVorteil, 0, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setStyleSheet("margin-left: 1px")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.plainText = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainText.setFrameShape(QtWidgets.QFrame.Box)
        self.plainText.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plainText.setLineWidth(1)
        self.plainText.setReadOnly(True)
        self.plainText.setBackgroundVisible(False)
        self.plainText.setObjectName("plainText")
        self.gridLayout.addWidget(self.plainText, 6, 0, 1, 2)
        self.labelTyp = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelTyp.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelTyp.setFont(font)
        self.labelTyp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTyp.setObjectName("labelTyp")
        self.gridLayout.addWidget(self.labelTyp, 2, 1, 1, 1)
        self.labelNachkauf = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelNachkauf.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelNachkauf.setFont(font)
        self.labelNachkauf.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNachkauf.setObjectName("labelNachkauf")
        self.gridLayout.addWidget(self.labelNachkauf, 3, 1, 1, 1)
        self.spinKosten = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinKosten.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinKosten.setReadOnly(True)
        self.spinKosten.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinKosten.setMinimum(-1000)
        self.spinKosten.setMaximum(1000)
        self.spinKosten.setSingleStep(20)
        self.spinKosten.setObjectName("spinKosten")
        self.gridLayout.addWidget(self.spinKosten, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.treeWidget, self.scrollArea)
        Dialog.setTabOrder(self.scrollArea, self.spinKosten)
        Dialog.setTabOrder(self.spinKosten, self.plainText)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sephrasto - Minderpakt-Vorteil wählen"))
        self.treeWidget.headerItem().setText(0, _translate("Dialog", "Vorteil"))
        self.treeWidget.headerItem().setText(1, _translate("Dialog", "Kosten"))
        self.labelVorteil.setText(_translate("Dialog", "Vorteil"))
        self.label.setText(_translate("Dialog", "Nachkauf:"))
        self.labelTyp.setText(_translate("Dialog", "Profan"))
        self.labelNachkauf.setText(_translate("Dialog", "Häufig"))
        self.spinKosten.setSuffix(_translate("Dialog", " EP"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
