# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CharakterBeschreibung.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_formBeschreibung(object):
    def setupUi(self, formBeschreibung):
        formBeschreibung.setObjectName("formBeschreibung")
        formBeschreibung.resize(701, 409)
        self.gridLayoutWidget = QtWidgets.QWidget(formBeschreibung)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 701, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.editKurzbeschreibung = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editKurzbeschreibung.setObjectName("editKurzbeschreibung")
        self.gridLayout.addWidget(self.editKurzbeschreibung, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.editEig1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editEig1.setMinimumSize(QtCore.QSize(200, 0))
        self.editEig1.setObjectName("editEig1")
        self.gridLayout_2.addWidget(self.editEig1, 0, 0, 1, 1)
        self.editEig6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editEig6.setMinimumSize(QtCore.QSize(200, 0))
        self.editEig6.setObjectName("editEig6")
        self.gridLayout_2.addWidget(self.editEig6, 2, 1, 1, 1)
        self.editEig3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editEig3.setMinimumSize(QtCore.QSize(200, 0))
        self.editEig3.setObjectName("editEig3")
        self.gridLayout_2.addWidget(self.editEig3, 1, 0, 1, 1)
        self.editEig5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editEig5.setMinimumSize(QtCore.QSize(200, 0))
        self.editEig5.setObjectName("editEig5")
        self.gridLayout_2.addWidget(self.editEig5, 2, 0, 1, 1)
        self.editEig4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editEig4.setMinimumSize(QtCore.QSize(200, 0))
        self.editEig4.setObjectName("editEig4")
        self.gridLayout_2.addWidget(self.editEig4, 1, 1, 1, 1)
        self.editEig2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editEig2.setMinimumSize(QtCore.QSize(200, 0))
        self.editEig2.setObjectName("editEig2")
        self.gridLayout_2.addWidget(self.editEig2, 0, 1, 1, 1)
        self.editEig7 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editEig7.setMinimumSize(QtCore.QSize(200, 0))
        self.editEig7.setObjectName("editEig7")
        self.gridLayout_2.addWidget(self.editEig7, 3, 0, 1, 1)
        self.editEig8 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editEig8.setMinimumSize(QtCore.QSize(200, 0))
        self.editEig8.setObjectName("editEig8")
        self.gridLayout_2.addWidget(self.editEig8, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 6, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.comboFinanzen = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboFinanzen.setMaxVisibleItems(5)
        self.comboFinanzen.setObjectName("comboFinanzen")
        self.comboFinanzen.addItem("")
        self.comboFinanzen.addItem("")
        self.comboFinanzen.addItem("")
        self.comboFinanzen.addItem("")
        self.comboFinanzen.addItem("")
        self.gridLayout.addWidget(self.comboFinanzen, 4, 2, 1, 1)
        self.comboStatus = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboStatus.setMaxVisibleItems(5)
        self.comboStatus.setMinimumContentsLength(0)
        self.comboStatus.setObjectName("comboStatus")
        self.comboStatus.addItem("")
        self.comboStatus.addItem("")
        self.comboStatus.addItem("")
        self.comboStatus.addItem("")
        self.comboStatus.addItem("")
        self.gridLayout.addWidget(self.comboStatus, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.editRasse = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editRasse.setObjectName("editRasse")
        self.gridLayout.addWidget(self.editRasse, 2, 2, 1, 1)
        self.editName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editName.setObjectName("editName")
        self.gridLayout.addWidget(self.editName, 1, 2, 1, 1)

        self.retranslateUi(formBeschreibung)
        self.comboFinanzen.setCurrentIndex(2)
        self.comboStatus.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(formBeschreibung)

    def retranslateUi(self, formBeschreibung):
        _translate = QtCore.QCoreApplication.translate
        formBeschreibung.setWindowTitle(_translate("formBeschreibung", "Beschreibung"))
        self.label_6.setText(_translate("formBeschreibung", "Eigenheiten"))
        self.label_4.setText(_translate("formBeschreibung", "Kurzbeschreibung"))
        self.label_5.setText(_translate("formBeschreibung", "Finanzen"))
        self.comboFinanzen.setItemText(0, _translate("formBeschreibung", "Sehr Reich"))
        self.comboFinanzen.setItemText(1, _translate("formBeschreibung", "Reich"))
        self.comboFinanzen.setItemText(2, _translate("formBeschreibung", "Normal"))
        self.comboFinanzen.setItemText(3, _translate("formBeschreibung", "Arm"))
        self.comboFinanzen.setItemText(4, _translate("formBeschreibung", "Sehr Arm"))
        self.comboStatus.setItemText(0, _translate("formBeschreibung", "Elite"))
        self.comboStatus.setItemText(1, _translate("formBeschreibung", "Oberschicht"))
        self.comboStatus.setItemText(2, _translate("formBeschreibung", "Mittelschicht"))
        self.comboStatus.setItemText(3, _translate("formBeschreibung", "Unterschicht"))
        self.comboStatus.setItemText(4, _translate("formBeschreibung", "Abschaum"))
        self.label_3.setText(_translate("formBeschreibung", "Status"))
        self.label.setText(_translate("formBeschreibung", "Name"))
        self.label_2.setText(_translate("formBeschreibung", "Rasse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formBeschreibung = QtWidgets.QWidget()
    ui = Ui_formBeschreibung()
    ui.setupUi(formBeschreibung)
    formBeschreibung.show()
    sys.exit(app.exec_())

