# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CharakterWaffen.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(814, 362)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("padding: 1px")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 296, 309))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelH = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelH.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelH.setObjectName("labelH")
        self.gridLayout.addWidget(self.labelH, 9, 2, 1, 1)
        self.labelWMLZ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelWMLZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelWMLZ.setObjectName("labelWMLZ")
        self.gridLayout.addWidget(self.labelWMLZ, 8, 2, 1, 1)
        self.labelRW = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelRW.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRW.setObjectName("labelRW")
        self.gridLayout.addWidget(self.labelRW, 7, 2, 1, 1)
        self.labelTP = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelTP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTP.setObjectName("labelTP")
        self.gridLayout.addWidget(self.labelTP, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.labelWMLZ_Text = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelWMLZ_Text.setObjectName("labelWMLZ_Text")
        self.gridLayout.addWidget(self.labelWMLZ_Text, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 10, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 2)
        self.labelTyp = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelTyp.setFont(font)
        self.labelTyp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTyp.setObjectName("labelTyp")
        self.gridLayout.addWidget(self.labelTyp, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 0, 1, 3)
        self.plainEigenschaften = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainEigenschaften.setReadOnly(True)
        self.plainEigenschaften.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainEigenschaften.setObjectName("plainEigenschaften")
        self.gridLayout.addWidget(self.plainEigenschaften, 11, 0, 1, 3)
        self.labelName = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 0, 0, 1, 2)
        self.plainStile = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainStile.setMaximumSize(QtCore.QSize(16777215, 50))
        self.plainStile.setReadOnly(True)
        self.plainStile.setObjectName("plainStile")
        self.gridLayout.addWidget(self.plainStile, 4, 0, 1, 3)
        self.labelFert = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelFert.setObjectName("labelFert")
        self.gridLayout.addWidget(self.labelFert, 3, 0, 1, 3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setObjectName("filterLayout")
        self.labelFilter = QtWidgets.QLabel(Dialog)
        self.labelFilter.setObjectName("labelFilter")
        self.filterLayout.addWidget(self.labelFilter)
        self.nameFilterEdit = QtWidgets.QLineEdit(Dialog)
        self.nameFilterEdit.setObjectName("nameFilterEdit")
        self.filterLayout.addWidget(self.nameFilterEdit)
        self.verticalLayout2.addLayout(self.filterLayout)
        self.treeWeapons = QtWidgets.QTreeWidget(Dialog)
        self.treeWeapons.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeWeapons.setProperty("showDropIndicator", False)
        self.treeWeapons.setAlternatingRowColors(True)
        self.treeWeapons.setAllColumnsShowFocus(True)
        self.treeWeapons.setObjectName("treeWeapons")
        self.treeWeapons.header().setVisible(True)
        self.treeWeapons.header().setCascadingSectionResizes(False)
        self.treeWeapons.header().setDefaultSectionSize(150)
        self.treeWeapons.header().setStretchLastSection(True)
        self.verticalLayout2.addWidget(self.treeWeapons)
        self.gridLayout_2.addLayout(self.verticalLayout2, 0, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.nameFilterEdit, self.treeWeapons)
        Dialog.setTabOrder(self.treeWeapons, self.scrollArea)
        Dialog.setTabOrder(self.scrollArea, self.plainStile)
        Dialog.setTabOrder(self.plainStile, self.plainEigenschaften)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sephrasto - Waffe wählen..."))
        self.labelH.setText(_translate("Dialog", "8"))
        self.labelWMLZ.setText(_translate("Dialog", "-1"))
        self.labelRW.setText(_translate("Dialog", "1"))
        self.labelTP.setText(_translate("Dialog", "2W6+2"))
        self.label_4.setText(_translate("Dialog", "Reichweite"))
        self.labelWMLZ_Text.setText(_translate("Dialog", "Waffenmodifikator"))
        self.label_2.setText(_translate("Dialog", "Trefferpunkte"))
        self.label_12.setText(_translate("Dialog", "Eigenschaften"))
        self.label_10.setText(_translate("Dialog", "Härte"))
        self.labelTyp.setText(_translate("Dialog", "Nah"))
        self.labelName.setText(_translate("Dialog", "Brabakbengel"))
        self.labelFert.setText(_translate("Dialog", "Hiebwaffen (Einhandhiebwaffen)"))
        self.labelFilter.setText(_translate("Dialog", "Suchen:"))
        self.treeWeapons.setSortingEnabled(False)
        self.treeWeapons.headerItem().setText(0, _translate("Dialog", "Name"))
        self.treeWeapons.headerItem().setText(1, _translate("Dialog", "Talent"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
