# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CharakterAttribute.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_formAttribute(object):
    def setupUi(self, formAttribute):
        formAttribute.setObjectName("formAttribute")
        formAttribute.resize(701, 409)
        self.gridLayoutWidget = QtWidgets.QWidget(formAttribute)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 701, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.pwKO = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.pwKO.setWrapping(False)
        self.pwKO.setFrame(True)
        self.pwKO.setAlignment(QtCore.Qt.AlignCenter)
        self.pwKO.setReadOnly(True)
        self.pwKO.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pwKO.setProperty("showGroupSeparator", False)
        self.pwKO.setObjectName("pwKO")
        self.gridLayout.addWidget(self.pwKO, 2, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 3, 1, 1)
        self.pwMU = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.pwMU.setWrapping(False)
        self.pwMU.setFrame(True)
        self.pwMU.setAlignment(QtCore.Qt.AlignCenter)
        self.pwMU.setReadOnly(True)
        self.pwMU.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pwMU.setProperty("showGroupSeparator", False)
        self.pwMU.setObjectName("pwMU")
        self.gridLayout.addWidget(self.pwMU, 3, 3, 1, 1)
        self.pwCH = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.pwCH.setWrapping(False)
        self.pwCH.setFrame(True)
        self.pwCH.setAlignment(QtCore.Qt.AlignCenter)
        self.pwCH.setReadOnly(True)
        self.pwCH.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pwCH.setProperty("showGroupSeparator", False)
        self.pwCH.setObjectName("pwCH")
        self.gridLayout.addWidget(self.pwCH, 8, 3, 1, 1)
        self.pwIN = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.pwIN.setWrapping(False)
        self.pwIN.setFrame(True)
        self.pwIN.setAlignment(QtCore.Qt.AlignCenter)
        self.pwIN.setReadOnly(True)
        self.pwIN.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pwIN.setProperty("showGroupSeparator", False)
        self.pwIN.setObjectName("pwIN")
        self.gridLayout.addWidget(self.pwIN, 6, 3, 1, 1)
        self.abSB = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.abSB.setWrapping(False)
        self.abSB.setFrame(True)
        self.abSB.setAlignment(QtCore.Qt.AlignCenter)
        self.abSB.setReadOnly(True)
        self.abSB.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.abSB.setProperty("showGroupSeparator", False)
        self.abSB.setObjectName("abSB")
        self.gridLayout.addWidget(self.abSB, 5, 6, 1, 1)
        self.pwKK = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.pwKK.setWrapping(False)
        self.pwKK.setFrame(True)
        self.pwKK.setAlignment(QtCore.Qt.AlignCenter)
        self.pwKK.setReadOnly(True)
        self.pwKK.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pwKK.setProperty("showGroupSeparator", False)
        self.pwKK.setObjectName("pwKK")
        self.gridLayout.addWidget(self.pwKK, 5, 3, 1, 1)
        self.pwKL = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.pwKL.setWrapping(False)
        self.pwKL.setFrame(True)
        self.pwKL.setAlignment(QtCore.Qt.AlignCenter)
        self.pwKL.setReadOnly(True)
        self.pwKL.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pwKL.setProperty("showGroupSeparator", False)
        self.pwKL.setObjectName("pwKL")
        self.gridLayout.addWidget(self.pwKL, 7, 3, 1, 1)
        self.pwGE = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.pwGE.setWrapping(False)
        self.pwGE.setFrame(True)
        self.pwGE.setAlignment(QtCore.Qt.AlignCenter)
        self.pwGE.setReadOnly(True)
        self.pwGE.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pwGE.setProperty("showGroupSeparator", False)
        self.pwGE.setObjectName("pwGE")
        self.gridLayout.addWidget(self.pwGE, 4, 3, 1, 1)
        self.abGS = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.abGS.setWrapping(False)
        self.abGS.setFrame(True)
        self.abGS.setAlignment(QtCore.Qt.AlignCenter)
        self.abGS.setReadOnly(True)
        self.abGS.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.abGS.setProperty("showGroupSeparator", False)
        self.abGS.setObjectName("abGS")
        self.gridLayout.addWidget(self.abGS, 4, 6, 1, 1)
        self.abMR = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.abMR.setWrapping(False)
        self.abMR.setFrame(True)
        self.abMR.setAlignment(QtCore.Qt.AlignCenter)
        self.abMR.setReadOnly(True)
        self.abMR.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.abMR.setProperty("showGroupSeparator", False)
        self.abMR.setObjectName("abMR")
        self.gridLayout.addWidget(self.abMR, 3, 6, 1, 1)
        self.abIN = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.abIN.setWrapping(False)
        self.abIN.setFrame(True)
        self.abIN.setAlignment(QtCore.Qt.AlignCenter)
        self.abIN.setReadOnly(True)
        self.abIN.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.abIN.setProperty("showGroupSeparator", False)
        self.abIN.setObjectName("abIN")
        self.gridLayout.addWidget(self.abIN, 6, 6, 1, 1)
        self.pwFF = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.pwFF.setWrapping(False)
        self.pwFF.setFrame(True)
        self.pwFF.setAlignment(QtCore.Qt.AlignCenter)
        self.pwFF.setReadOnly(True)
        self.pwFF.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pwFF.setProperty("showGroupSeparator", False)
        self.pwFF.setObjectName("pwFF")
        self.gridLayout.addWidget(self.pwFF, 9, 3, 1, 1)
        self.spinMU = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinMU.setAlignment(QtCore.Qt.AlignCenter)
        self.spinMU.setReadOnly(False)
        self.spinMU.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinMU.setObjectName("spinMU")
        self.gridLayout.addWidget(self.spinMU, 3, 2, 1, 1)
        self.abWS = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.abWS.setWrapping(False)
        self.abWS.setFrame(True)
        self.abWS.setAlignment(QtCore.Qt.AlignCenter)
        self.abWS.setReadOnly(True)
        self.abWS.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.abWS.setProperty("showGroupSeparator", False)
        self.abWS.setObjectName("abWS")
        self.gridLayout.addWidget(self.abWS, 2, 6, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 1, 2, 1, 1)
        self.spinIN = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinIN.setAlignment(QtCore.Qt.AlignCenter)
        self.spinIN.setReadOnly(False)
        self.spinIN.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinIN.setObjectName("spinIN")
        self.gridLayout.addWidget(self.spinIN, 6, 2, 1, 1)
        self.spinAsP = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinAsP.setAlignment(QtCore.Qt.AlignCenter)
        self.spinAsP.setReadOnly(False)
        self.spinAsP.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinAsP.setObjectName("spinAsP")
        self.gridLayout.addWidget(self.spinAsP, 8, 6, 1, 1)
        self.spinFF = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinFF.setAlignment(QtCore.Qt.AlignCenter)
        self.spinFF.setReadOnly(False)
        self.spinFF.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinFF.setObjectName("spinFF")
        self.gridLayout.addWidget(self.spinFF, 9, 2, 1, 1)
        self.spinKL = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinKL.setAlignment(QtCore.Qt.AlignCenter)
        self.spinKL.setReadOnly(False)
        self.spinKL.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinKL.setObjectName("spinKL")
        self.gridLayout.addWidget(self.spinKL, 7, 2, 1, 1)
        self.spinCH = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinCH.setAlignment(QtCore.Qt.AlignCenter)
        self.spinCH.setReadOnly(False)
        self.spinCH.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinCH.setObjectName("spinCH")
        self.gridLayout.addWidget(self.spinCH, 8, 2, 1, 1)
        self.spinKaP = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinKaP.setAlignment(QtCore.Qt.AlignCenter)
        self.spinKaP.setReadOnly(False)
        self.spinKaP.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinKaP.setObjectName("spinKaP")
        self.gridLayout.addWidget(self.spinKaP, 9, 6, 1, 1)
        self.spinGE = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinGE.setAlignment(QtCore.Qt.AlignCenter)
        self.spinGE.setReadOnly(False)
        self.spinGE.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinGE.setObjectName("spinGE")
        self.gridLayout.addWidget(self.spinGE, 4, 2, 1, 1)
        self.spinKK = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinKK.setAlignment(QtCore.Qt.AlignCenter)
        self.spinKK.setReadOnly(False)
        self.spinKK.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinKK.setObjectName("spinKK")
        self.gridLayout.addWidget(self.spinKK, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 1, 1, 1)
        self.spinKO = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinKO.setAlignment(QtCore.Qt.AlignCenter)
        self.spinKO.setReadOnly(False)
        self.spinKO.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinKO.setObjectName("spinKO")
        self.gridLayout.addWidget(self.spinKO, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 7, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 8, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(100, 0))
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 9, 5, 1, 1)

        self.retranslateUi(formAttribute)
        QtCore.QMetaObject.connectSlotsByName(formAttribute)

    def retranslateUi(self, formAttribute):
        _translate = QtCore.QCoreApplication.translate
        formAttribute.setWindowTitle(_translate("formAttribute", "Attribute"))
        self.label.setText(_translate("formAttribute", "Konstitution"))
        self.label_17.setText(_translate("formAttribute", "PW"))
        self.label_16.setText(_translate("formAttribute", "Wert"))
        self.label_2.setText(_translate("formAttribute", "Mut"))
        self.label_7.setText(_translate("formAttribute", "Charisma"))
        self.label_5.setText(_translate("formAttribute", "Intuition"))
        self.label_8.setText(_translate("formAttribute", "Fingerfertigkeit"))
        self.label_6.setText(_translate("formAttribute", "Klugheit"))
        self.label_3.setText(_translate("formAttribute", "Gewandheit"))
        self.label_9.setText(_translate("formAttribute", "Wundschwelle"))
        self.label_4.setText(_translate("formAttribute", "Körperkraft"))
        self.label_13.setText(_translate("formAttribute", "Initiative"))
        self.label_12.setText(_translate("formAttribute", "Schadensbonus"))
        self.label_11.setText(_translate("formAttribute", "Geschwindigkeit"))
        self.label_14.setText(_translate("formAttribute", "Astralenergie"))
        self.label_10.setText(_translate("formAttribute", "Magieresistenz"))
        self.label_15.setText(_translate("formAttribute", "Karmalenergie"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formAttribute = QtWidgets.QWidget()
    ui = Ui_formAttribute()
    ui.setupUi(formAttribute)
    formAttribute.show()
    sys.exit(app.exec_())

