# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DatenbankEditFertigkeit.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets
import Fertigkeiten
from Hilfsmethoden import Hilfsmethoden

class Ui_fertigkeitDialog(object):
    def setupUi(self, fertigkeitDialog):
        fertigkeitDialog.setObjectName("fertigkeitDialog")
        fertigkeitDialog.resize(379, 303)
        self.buttonBox = QtWidgets.QDialogButtonBox(fertigkeitDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 271, 361, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(fertigkeitDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.nameEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioProfan = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioProfan.setAutoFillBackground(False)
        self.radioProfan.setCheckable(True)
        self.radioProfan.setObjectName("radioProfan")
        self.horizontalLayout_4.addWidget(self.radioProfan)
        self.checkKampffertigkeit = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkKampffertigkeit.setObjectName("checkKampffertigkeit")
        self.horizontalLayout_4.addWidget(self.checkKampffertigkeit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.radioUebernatuerlich = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioUebernatuerlich.setObjectName("radioUebernatuerlich")
        self.verticalLayout.addWidget(self.radioUebernatuerlich)
        self.voraussetzungenEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.voraussetzungenEdit.setObjectName("voraussetzungenEdit")
        self.verticalLayout.addWidget(self.voraussetzungenEdit)
        self.gridLayout.addLayout(self.verticalLayout, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboAttribut1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboAttribut1.setObjectName("comboAttribut1")
        self.comboAttribut1.addItem("")
        self.comboAttribut1.addItem("")
        self.comboAttribut1.addItem("")
        self.comboAttribut1.addItem("")
        self.comboAttribut1.addItem("")
        self.comboAttribut1.addItem("")
        self.comboAttribut1.addItem("")
        self.comboAttribut1.addItem("")
        self.horizontalLayout.addWidget(self.comboAttribut1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.comboAttribut2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboAttribut2.setObjectName("comboAttribut2")
        self.comboAttribut2.addItem("")
        self.comboAttribut2.addItem("")
        self.comboAttribut2.addItem("")
        self.comboAttribut2.addItem("")
        self.comboAttribut2.addItem("")
        self.comboAttribut2.addItem("")
        self.comboAttribut2.addItem("")
        self.comboAttribut2.addItem("")
        self.horizontalLayout.addWidget(self.comboAttribut2)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.comboAttribut3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboAttribut3.setObjectName("comboAttribut3")
        self.comboAttribut3.addItem("")
        self.comboAttribut3.addItem("")
        self.comboAttribut3.addItem("")
        self.comboAttribut3.addItem("")
        self.comboAttribut3.addItem("")
        self.comboAttribut3.addItem("")
        self.comboAttribut3.addItem("")
        self.comboAttribut3.addItem("")
        self.horizontalLayout.addWidget(self.comboAttribut3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.textEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.steigerungsfaktorEdit = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.steigerungsfaktorEdit.setSuffix("")
        self.steigerungsfaktorEdit.setMinimum(0)
        self.steigerungsfaktorEdit.setMaximum(4)
        self.steigerungsfaktorEdit.setSingleStep(1)
        self.steigerungsfaktorEdit.setProperty("value", 2)
        self.steigerungsfaktorEdit.setObjectName("steigerungsfaktorEdit")
        self.horizontalLayout_2.addWidget(self.steigerungsfaktorEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)

        self.retranslateUi(fertigkeitDialog)
        self.buttonBox.accepted.connect(fertigkeitDialog.accept)
        self.buttonBox.rejected.connect(fertigkeitDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(fertigkeitDialog)
        fertigkeitDialog.setTabOrder(self.nameEdit, self.steigerungsfaktorEdit)
        fertigkeitDialog.setTabOrder(self.steigerungsfaktorEdit, self.comboAttribut1)
        fertigkeitDialog.setTabOrder(self.comboAttribut1, self.comboAttribut2)
        fertigkeitDialog.setTabOrder(self.comboAttribut2, self.comboAttribut3)
        fertigkeitDialog.setTabOrder(self.comboAttribut3, self.radioProfan)
        fertigkeitDialog.setTabOrder(self.radioProfan, self.checkKampffertigkeit)
        fertigkeitDialog.setTabOrder(self.checkKampffertigkeit, self.radioUebernatuerlich)
        fertigkeitDialog.setTabOrder(self.radioUebernatuerlich, self.voraussetzungenEdit)
        fertigkeitDialog.setTabOrder(self.voraussetzungenEdit, self.textEdit)

    def retranslateUi(self, fertigkeitDialog):
        _translate = QtCore.QCoreApplication.translate
        fertigkeitDialog.setWindowTitle(_translate("fertigkeitDialog", "Fertigkeits-Editor"))
        self.label.setText(_translate("fertigkeitDialog", "Fertigkeitsname"))
        self.radioProfan.setText(_translate("fertigkeitDialog", "Profan"))
        self.checkKampffertigkeit.setText(_translate("fertigkeitDialog", "Kampffertigkeit"))
        self.radioUebernatuerlich.setText(_translate("fertigkeitDialog", "Übernatürlich mit Voraussetzungen:"))
        self.label_2.setText(_translate("fertigkeitDialog", "Steigerungsfaktor"))
        self.comboAttribut1.setItemText(0, _translate("fertigkeitDialog", "KO"))
        self.comboAttribut1.setItemText(1, _translate("fertigkeitDialog", "MU"))
        self.comboAttribut1.setItemText(2, _translate("fertigkeitDialog", "GE"))
        self.comboAttribut1.setItemText(3, _translate("fertigkeitDialog", "KK"))
        self.comboAttribut1.setItemText(4, _translate("fertigkeitDialog", "IN"))
        self.comboAttribut1.setItemText(5, _translate("fertigkeitDialog", "KL"))
        self.comboAttribut1.setItemText(6, _translate("fertigkeitDialog", "CH"))
        self.comboAttribut1.setItemText(7, _translate("fertigkeitDialog", "FF"))
        self.label_6.setText(_translate("fertigkeitDialog", " - "))
        self.comboAttribut2.setItemText(0, _translate("fertigkeitDialog", "KO"))
        self.comboAttribut2.setItemText(1, _translate("fertigkeitDialog", "MU"))
        self.comboAttribut2.setItemText(2, _translate("fertigkeitDialog", "GE"))
        self.comboAttribut2.setItemText(3, _translate("fertigkeitDialog", "KK"))
        self.comboAttribut2.setItemText(4, _translate("fertigkeitDialog", "IN"))
        self.comboAttribut2.setItemText(5, _translate("fertigkeitDialog", "KL"))
        self.comboAttribut2.setItemText(6, _translate("fertigkeitDialog", "CH"))
        self.comboAttribut2.setItemText(7, _translate("fertigkeitDialog", "FF"))
        self.label_7.setText(_translate("fertigkeitDialog", " - "))
        self.comboAttribut3.setItemText(0, _translate("fertigkeitDialog", "KO"))
        self.comboAttribut3.setItemText(1, _translate("fertigkeitDialog", "MU"))
        self.comboAttribut3.setItemText(2, _translate("fertigkeitDialog", "GE"))
        self.comboAttribut3.setItemText(3, _translate("fertigkeitDialog", "KK"))
        self.comboAttribut3.setItemText(4, _translate("fertigkeitDialog", "IN"))
        self.comboAttribut3.setItemText(5, _translate("fertigkeitDialog", "KL"))
        self.comboAttribut3.setItemText(6, _translate("fertigkeitDialog", "CH"))
        self.comboAttribut3.setItemText(7, _translate("fertigkeitDialog", "FF"))
        self.label_3.setText(_translate("fertigkeitDialog", "Attribute"))
        self.label_5.setText(_translate("fertigkeitDialog", "Text"))
        self.label_4.setText(_translate("fertigkeitDialog", "Fertigkeitstyp"))
    
    def createFertigkeit(self):
        fer = Fertigkeiten.Fertigkeit()
        fer.name = self.nameEdit.text()
        fer.steigerungsfaktor = int(self.steigerungsfaktorEdit.value())
        if self.radioProfan.isChecked():
            if self.checkKampffertigkeit.isChecked():
                fer.kampffertigkeit = 1;
        else:
            fer.voraussetzungen = Hilfsmethoden.VorStr2Array(self.voraussetzungenEdit.text(),None)
        fer.attribute = [self.comboAttribut1.currentText(), 
                         self.comboAttribut2.currentText(),
                         self.comboAttribut3.currentText()]
        fer.text = self.textEdit.toPlainText()
        return fer

if __name__ == "__main__":
    import sys
    app = QtCore.QCoreApplication.instance()
    if app is None:
        app = QtWidgets.QApplication(sys.argv)
    fertigkeitDialog = QtWidgets.QDialog()
    ui = Ui_fertigkeitDialog()
    ui.setupUi(fertigkeitDialog)
    fertigkeitDialog.show()
    sys.exit(app.exec_())

