# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DatenbankEditVorteil.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_talentDialog(object):
    def setupUi(self, talentDialog):
        talentDialog.setObjectName("talentDialog")
        talentDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        talentDialog.resize(440, 550)
        self.gridLayout_2 = QtWidgets.QGridLayout(talentDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(talentDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.comboNachkauf = QtWidgets.QComboBox(talentDialog)
        self.comboNachkauf.setObjectName("comboNachkauf")
        self.comboNachkauf.addItem("")
        self.comboNachkauf.addItem("")
        self.comboNachkauf.addItem("")
        self.comboNachkauf.addItem("")
        self.comboNachkauf.addItem("")
        self.horizontalLayout.addWidget(self.comboNachkauf)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.textEdit = QtWidgets.QPlainTextEdit(talentDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.checkVariable = QtWidgets.QCheckBox(talentDialog)
        self.checkVariable.setObjectName("checkVariable")
        self.horizontalLayout_2.addWidget(self.checkVariable)
        self.kostenEdit = QtWidgets.QSpinBox(talentDialog)
        self.kostenEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.kostenEdit.setMinimum(-1000)
        self.kostenEdit.setMaximum(1000)
        self.kostenEdit.setSingleStep(20)
        self.kostenEdit.setProperty("value", 40)
        self.kostenEdit.setObjectName("kostenEdit")
        self.horizontalLayout_2.addWidget(self.kostenEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(talentDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(talentDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(talentDialog)
        self.label_4.setMinimumSize(QtCore.QSize(110, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(talentDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(talentDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(talentDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboTyp = QtWidgets.QComboBox(talentDialog)
        self.comboTyp.setObjectName("comboTyp")
        self.comboTyp.addItem("")
        self.comboTyp.addItem("")
        self.comboTyp.addItem("")
        self.comboTyp.addItem("")
        self.comboTyp.addItem("")
        self.comboTyp.addItem("")
        self.comboTyp.addItem("")
        self.comboTyp.addItem("")
        self.horizontalLayout_3.addWidget(self.comboTyp)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        self.voraussetzungenEdit = QtWidgets.QPlainTextEdit(talentDialog)
        self.voraussetzungenEdit.setObjectName("voraussetzungenEdit")
        self.gridLayout.addWidget(self.voraussetzungenEdit, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(talentDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(talentDialog)
        self.buttonBox.accepted.connect(talentDialog.accept)
        self.buttonBox.rejected.connect(talentDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(talentDialog)
        talentDialog.setTabOrder(self.nameEdit, self.checkVariable)
        talentDialog.setTabOrder(self.checkVariable, self.kostenEdit)
        talentDialog.setTabOrder(self.kostenEdit, self.comboNachkauf)
        talentDialog.setTabOrder(self.comboNachkauf, self.voraussetzungenEdit)
        talentDialog.setTabOrder(self.voraussetzungenEdit, self.comboTyp)
        talentDialog.setTabOrder(self.comboTyp, self.textEdit)

    def retranslateUi(self, talentDialog):
        _translate = QtCore.QCoreApplication.translate
        talentDialog.setWindowTitle(_translate("talentDialog", "Sephrasto - Vorteil bearbeiten..."))
        self.label_2.setText(_translate("talentDialog", "Lernkosten"))
        self.comboNachkauf.setItemText(0, _translate("talentDialog", "häufig"))
        self.comboNachkauf.setItemText(1, _translate("talentDialog", "üblich"))
        self.comboNachkauf.setItemText(2, _translate("talentDialog", "selten"))
        self.comboNachkauf.setItemText(3, _translate("talentDialog", "extrem selten"))
        self.comboNachkauf.setItemText(4, _translate("talentDialog", "nicht möglich"))
        self.checkVariable.setText(_translate("talentDialog", "Variabel"))
        self.kostenEdit.setSuffix(_translate("talentDialog", " EP"))
        self.label_5.setText(_translate("talentDialog", "Beschreibung"))
        self.label.setText(_translate("talentDialog", "Vorteilsname"))
        self.label_4.setText(_translate("talentDialog", "Voraussetzungen"))
        self.label_3.setText(_translate("talentDialog", "Nachkauf"))
        self.label_6.setText(_translate("talentDialog", "Typ"))
        self.comboTyp.setItemText(0, _translate("talentDialog", "Allgemeiner Vorteil"))
        self.comboTyp.setItemText(1, _translate("talentDialog", "Profaner Vorteil"))
        self.comboTyp.setItemText(2, _translate("talentDialog", "Kampfvorteil"))
        self.comboTyp.setItemText(3, _translate("talentDialog", "Kampfstil"))
        self.comboTyp.setItemText(4, _translate("talentDialog", "Magischer Vorteil"))
        self.comboTyp.setItemText(5, _translate("talentDialog", "Repräsentation"))
        self.comboTyp.setItemText(6, _translate("talentDialog", "Karmaler Vorteil"))
        self.comboTyp.setItemText(7, _translate("talentDialog", "Tradition"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    talentDialog = QtWidgets.QDialog()
    ui = Ui_talentDialog()
    ui.setupUi(talentDialog)
    talentDialog.show()
    sys.exit(app.exec_())

