# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DatenbankEditWaffe.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_talentDialog(object):
    def setupUi(self, talentDialog):
        talentDialog.setObjectName("talentDialog")
        talentDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        talentDialog.resize(440, 370)
        self.gridLayout_2 = QtWidgets.QGridLayout(talentDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.textEigenschaften = QtWidgets.QPlainTextEdit(talentDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEigenschaften.sizePolicy().hasHeightForWidth())
        self.textEigenschaften.setSizePolicy(sizePolicy)
        self.textEigenschaften.setObjectName("textEigenschaften")
        self.gridLayout.addWidget(self.textEigenschaften, 6, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.spinW6 = QtWidgets.QSpinBox(talentDialog)
        self.spinW6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinW6.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinW6.setMinimum(1)
        self.spinW6.setMaximum(9)
        self.spinW6.setProperty("value", 2)
        self.spinW6.setObjectName("spinW6")
        self.horizontalLayout.addWidget(self.spinW6)
        self.label_7 = QtWidgets.QLabel(talentDialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.spinPlus = QtWidgets.QSpinBox(talentDialog)
        self.spinPlus.setAlignment(QtCore.Qt.AlignCenter)
        self.spinPlus.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinPlus.setMinimum(-9)
        self.spinPlus.setProperty("value", 2)
        self.spinPlus.setObjectName("spinPlus")
        self.horizontalLayout.addWidget(self.spinPlus)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.spinWMLZ = QtWidgets.QSpinBox(talentDialog)
        self.spinWMLZ.setAlignment(QtCore.Qt.AlignCenter)
        self.spinWMLZ.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinWMLZ.setMinimum(-9)
        self.spinWMLZ.setMaximum(99)
        self.spinWMLZ.setObjectName("spinWMLZ")
        self.horizontalLayout_5.addWidget(self.spinWMLZ)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(talentDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(talentDialog)
        self.label_4.setMinimumSize(QtCore.QSize(110, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(talentDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.labelWMLZ = QtWidgets.QLabel(talentDialog)
        self.labelWMLZ.setObjectName("labelWMLZ")
        self.gridLayout.addWidget(self.labelWMLZ, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(talentDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(talentDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(talentDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboTyp = QtWidgets.QComboBox(talentDialog)
        self.comboTyp.setObjectName("comboTyp")
        self.comboTyp.addItem("")
        self.comboTyp.addItem("")
        self.horizontalLayout_2.addWidget(self.comboTyp)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.spinRW1 = QtWidgets.QSpinBox(talentDialog)
        self.spinRW1.setAlignment(QtCore.Qt.AlignCenter)
        self.spinRW1.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinRW1.setMaximum(999)
        self.spinRW1.setProperty("value", 1)
        self.spinRW1.setObjectName("spinRW1")
        self.horizontalLayout_4.addWidget(self.spinRW1)
        self.labelRW = QtWidgets.QLabel(talentDialog)
        self.labelRW.setObjectName("labelRW")
        self.horizontalLayout_4.addWidget(self.labelRW)
        self.spinRW2 = QtWidgets.QSpinBox(talentDialog)
        self.spinRW2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinRW2.setMaximum(999)
        self.spinRW2.setProperty("value", 16)
        self.spinRW2.setObjectName("spinRW2")
        self.horizontalLayout_4.addWidget(self.spinRW2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(talentDialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.spinHaerte = QtWidgets.QSpinBox(talentDialog)
        self.spinHaerte.setAlignment(QtCore.Qt.AlignCenter)
        self.spinHaerte.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinHaerte.setMinimum(0)
        self.spinHaerte.setProperty("value", 7)
        self.spinHaerte.setObjectName("spinHaerte")
        self.horizontalLayout_6.addWidget(self.spinHaerte)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(talentDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(talentDialog)
        self.buttonBox.accepted.connect(talentDialog.accept)
        self.buttonBox.rejected.connect(talentDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(talentDialog)
        talentDialog.setTabOrder(self.nameEdit, self.textEigenschaften)

    def retranslateUi(self, talentDialog):
        _translate = QtCore.QCoreApplication.translate
        talentDialog.setWindowTitle(_translate("talentDialog", "Sephrasto - Waffe bearbeiten..."))
        self.spinW6.setSuffix(_translate("talentDialog", " W6"))
        self.label_7.setText(_translate("talentDialog", "+"))
        self.label_3.setText(_translate("talentDialog", "Trefferpunkte"))
        self.label_4.setText(_translate("talentDialog", "Reichweite"))
        self.labelWMLZ.setText(_translate("talentDialog", "WM/LZ"))
        self.label_2.setText(_translate("talentDialog", "Typ"))
        self.label.setText(_translate("talentDialog", "Waffenname"))
        self.label_5.setText(_translate("talentDialog", "Eigenschaften"))
        self.comboTyp.setItemText(0, _translate("talentDialog", "Nahkampfwaffe"))
        self.comboTyp.setItemText(1, _translate("talentDialog", "Fernkampfwaffe"))
        self.labelRW.setText(_translate("talentDialog", "/"))
        self.label_9.setText(_translate("talentDialog", "Härte"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    talentDialog = QtWidgets.QDialog()
    ui = Ui_talentDialog()
    ui.setupUi(talentDialog)
    talentDialog.show()
    sys.exit(app.exec_())

