[tool.poetry]
name = "sephrasto"
version = "2.6.0"
description = "Ein Charaktergenerator für das DSA-Hausregelsystem Ilaris."
authors = ["Aeolitus", "brzGatsu"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.7"
lxml = "^4.9.1"
PyQt5 = "^5.15.6"
PyYAML = "^6.0"
requests = "^2.26"

[tool.poetry.dev-dependencies]
cx-Freeze = "^6.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
