# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CharakterFreieFertigkeitenPicker.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(461, 522)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalLayout_2.sizePolicy().hasHeightForWidth())
        self.verticalLayout_2.setSizePolicy(sizePolicy)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout2 = QtWidgets.QVBoxLayout(self.verticalLayout_2)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.label = QtWidgets.QLabel(self.verticalLayout_2)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelFilter = QtWidgets.QLabel(self.verticalLayout_2)
        self.labelFilter.setObjectName("labelFilter")
        self.horizontalLayout.addWidget(self.labelFilter)
        self.nameFilterEdit = QtWidgets.QLineEdit(self.verticalLayout_2)
        self.nameFilterEdit.setObjectName("nameFilterEdit")
        self.horizontalLayout.addWidget(self.nameFilterEdit)
        self.verticalLayout2.addLayout(self.horizontalLayout)
        self.treeFerts = QtWidgets.QTreeWidget(self.verticalLayout_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeFerts.sizePolicy().hasHeightForWidth())
        self.treeFerts.setSizePolicy(sizePolicy)
        self.treeFerts.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeFerts.setProperty("showDropIndicator", False)
        self.treeFerts.setAlternatingRowColors(True)
        self.treeFerts.setAllColumnsShowFocus(True)
        self.treeFerts.setObjectName("treeFerts")
        self.treeFerts.header().setVisible(True)
        self.treeFerts.header().setCascadingSectionResizes(False)
        self.treeFerts.header().setDefaultSectionSize(150)
        self.treeFerts.header().setStretchLastSection(True)
        self.verticalLayout2.addWidget(self.treeFerts)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayout_2)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout2.addWidget(self.buttonBox)
        self.gridLayout.addWidget(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.nameFilterEdit, self.treeFerts)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sephrasto - Freie Fertigkeit wählen..."))
        self.label.setText(_translate("Dialog", "Inoffiziell: Bei den aufgeführten Sprachen und Schriften handelt es sich um an WdS orientierte Vorschläge."))
        self.labelFilter.setText(_translate("Dialog", "Suchen:"))
        self.treeFerts.setSortingEnabled(False)
        self.treeFerts.headerItem().setText(0, _translate("Dialog", "Freie Fertigkeit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
