# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DatenbankEditFreieFertigkeit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ffDialog(object):
    def setupUi(self, ffDialog):
        ffDialog.setObjectName("ffDialog")
        ffDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ffDialog.resize(440, 204)
        self.gridLayout_2 = QtWidgets.QGridLayout(ffDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(ffDialog)
        self.label_4.setMinimumSize(QtCore.QSize(110, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.teVoraussetzungen = QtWidgets.QPlainTextEdit(ffDialog)
        self.teVoraussetzungen.setObjectName("teVoraussetzungen")
        self.gridLayout.addWidget(self.teVoraussetzungen, 3, 1, 1, 1)
        self.warning = QtWidgets.QLabel(ffDialog)
        self.warning.setVisible(False)
        self.warning.setStyleSheet("background-color: rgb(255, 255, 0); color: black;")
        self.warning.setWordWrap(True)
        self.warning.setObjectName("warning")
        self.gridLayout.addWidget(self.warning, 0, 0, 1, 2)
        self.leName = QtWidgets.QLineEdit(ffDialog)
        self.leName.setObjectName("leName")
        self.gridLayout.addWidget(self.leName, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(ffDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(ffDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.comboTyp = QtWidgets.QComboBox(ffDialog)
        self.comboTyp.setObjectName("comboTyp")
        self.gridLayout.addWidget(self.comboTyp, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ffDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(ffDialog)
        self.buttonBox.accepted.connect(ffDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ffDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ffDialog)
        ffDialog.setTabOrder(self.leName, self.comboTyp)
        ffDialog.setTabOrder(self.comboTyp, self.teVoraussetzungen)

    def retranslateUi(self, ffDialog):
        _translate = QtCore.QCoreApplication.translate
        ffDialog.setWindowTitle(_translate("ffDialog", "Sephrasto - Freie Fertigkeit bearbeiten..."))
        self.label_4.setText(_translate("ffDialog", "Voraussetzungen"))
        self.warning.setText(_translate("ffDialog", "<html><head/><body><p>Dies ist eine Ilaris Standard-Freie-Fertigkeit. Sobald du hier etwas veränderst, bekommst du eine persönliche Kopie und das Original wird in den Hausregeln gelöscht. Damit erhältst du für diese Freie Fertigkeit keine automatischen Updates mehr mit neuen Sephrasto-Versionen.</p></body></html>"))
        self.label.setText(_translate("ffDialog", "Name"))
        self.label_2.setText(_translate("ffDialog", "Typ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ffDialog = QtWidgets.QDialog()
    ui = Ui_ffDialog()
    ui.setupUi(ffDialog)
    ffDialog.show()
    sys.exit(app.exec_())
