# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(286, 346)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonNew = QtWidgets.QPushButton(Form)
        self.buttonNew.setObjectName("buttonNew")
        self.gridLayout.addWidget(self.buttonNew, 7, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 19, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.buttonEdit = QtWidgets.QPushButton(Form)
        self.buttonEdit.setObjectName("buttonEdit")
        self.gridLayout.addWidget(self.buttonEdit, 8, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.buttonHelp = QtWidgets.QPushButton(Form)
        self.buttonHelp.setMinimumSize(QtCore.QSize(28, 28))
        self.buttonHelp.setMaximumSize(QtCore.QSize(28, 28))
        self.buttonHelp.setObjectName("buttonHelp")
        self.horizontalLayout.addWidget(self.buttonHelp)
        self.buttonSettings = QtWidgets.QPushButton(Form)
        self.buttonSettings.setMinimumSize(QtCore.QSize(28, 28))
        self.buttonSettings.setMaximumSize(QtCore.QSize(28, 28))
        self.buttonSettings.setObjectName("buttonSettings")
        self.horizontalLayout.addWidget(self.buttonSettings)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.vlPluginButtons = QtWidgets.QVBoxLayout()
        self.vlPluginButtons.setObjectName("vlPluginButtons")
        self.gridLayout.addLayout(self.vlPluginButtons, 15, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 13, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 6, 0, 1, 1)
        self.labelVersion = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        self.labelVersion.setFont(font)
        self.labelVersion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelVersion.setObjectName("labelVersion")
        self.gridLayout.addWidget(self.labelVersion, 24, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 10, 0, 1, 1)
        self.buttonRules = QtWidgets.QPushButton(Form)
        self.buttonRules.setObjectName("buttonRules")
        self.gridLayout.addWidget(self.buttonRules, 9, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.buttonNew, self.buttonEdit)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Sephrasto"))
        self.buttonNew.setText(_translate("Form", "Neuen Charakter erstellen"))
        self.label_2.setText(_translate("Form", "Ein Charaktergenerator für Ilaris"))
        self.buttonEdit.setText(_translate("Form", "Charakter laden"))
        self.buttonHelp.setText(_translate("Form", "Hilfe"))
        self.buttonHelp.setProperty("class", _translate("Form", "icon"))
        self.buttonSettings.setText(_translate("Form", "Einst"))
        self.buttonSettings.setProperty("class", _translate("Form", "icon"))
        self.label.setText(_translate("Form", "Sephrasto"))
        self.label.setProperty("class", _translate("Form", "title"))
        self.labelVersion.setText(_translate("Form", "PLACEHOLDER"))
        self.labelVersion.setProperty("class", _translate("Form", "smallText"))
        self.buttonRules.setText(_translate("Form", "Regelbasis bearbeiten"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
